---
- name: Manually Install and Configure Ollama (The Right Way)
  hosts: llm_server
  become: true
  tasks:
    # ===================================================================
    # STEP 1: COMPLETE CLEANUP
    # ===================================================================
    - name: 1.1. Stop and disable the Ollama service
      ansible.builtin.systemd:
        name: ollama
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: 1.2. Find the path of the ollama binary
      ansible.builtin.command: which ollama
      register: ollama_path_result
      failed_when: false
      changed_when: false

    - name: 1.3. Remove the ollama binary if it exists
      ansible.builtin.file:
        path: "{{ ollama_path_result.stdout }}"
        state: absent
      when: ollama_path_result.rc == 0

    - name: 1.4. Remove the ollama libraries if they exist
      ansible.builtin.file:
        path: /usr/lib/ollama
        state: absent
      
    - name: 1.5. Remove the ollama service file
      ansible.builtin.file:
        path: /etc/systemd/system/ollama.service
        state: absent

    - name: 1.6. Remove the ollama service override files
      ansible.builtin.file:
        path: /etc/systemd/system/ollama.service.d
        state: absent

    - name: 1.7. Remove ollama user data and models
      ansible.builtin.file:
        path: /usr/share/ollama
        state: absent

    - name: 1.8. Remove the ollama user and group
      ansible.builtin.user:
        name: ollama
        state: absent
        remove: yes
      ignore_errors: yes
    
    # ===================================================================
    # STEP 2: CLEAN MANUAL INSTALLATION
    # ===================================================================
    - name: 2.1. Create the ollama group
      ansible.builtin.group:
        name: ollama
        state: present

    - name: 2.2. Create the ollama system user
      ansible.builtin.user:
        name: ollama
        comment: Ollama Service User
        group: ollama
        home: /usr/share/ollama
        create_home: yes
        system: yes
        shell: /bin/false

    - name: 2.3. Download and unarchive Ollama from the official .tgz
      ansible.builtin.unarchive:
        src: https://ollama.com/download/ollama-linux-amd64.tgz
        dest: /usr/bin
        remote_src: yes
        owner: root
        group: root
        mode: '0755'
        
    - name: 2.4. Create the systemd service file for Ollama
      ansible.builtin.copy:
        dest: /etc/systemd/system/ollama.service
        content: |
          [Unit]
          Description=Ollama Service
          After=network-online.target

          [Service]
          ExecStart=/usr/bin/ollama serve
          User=ollama
          Group=ollama
          Restart=always
          RestartSec=3
          Environment="HOME=/usr/share/ollama"
          Environment="OLLAMA_HOST=0.0.0.0"

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: 2.5. Reload systemd, enable and start the ollama service
      ansible.builtin.systemd:
        daemon_reload: yes
        name: ollama
        state: started
        enabled: yes